(function (global) {
  "use strict";
  function createController(stage,overlay,configuration){
    const options=Object.assign({sourceWidth:1,sourceHeight:1,onChange:function(){}},configuration||{});let mode="select",selector=null,operation=null;
    const clamp=v=>Math.max(0,Math.min(1,v));
    function position(event){const r=stage.getBoundingClientRect();return{x:clamp((event.clientX-r.left)/r.width),y:clamp((event.clientY-r.top)/r.height)};}
    function copy(){return selector?JSON.parse(JSON.stringify(selector)):null;} function emit(){options.onChange(copy());}
    function svg(name){return document.createElementNS("http://www.w3.org/2000/svg",name);}
    function draw(){overlay.replaceChildren();if(!selector)return;if(selector.type.endsWith("PointSelector")){selector.points.forEach(function(p,i){const m=svg("circle");m.setAttribute("cx",p.x*options.sourceWidth);m.setAttribute("cy",p.y*options.sourceHeight);m.setAttribute("r",9);m.dataset.geometryIndex=i;m.dataset.geometryAction="move-point";m.classList.add("ontobdc-annotation-geometry-point");overlay.append(m);});return;}const box=svg("rect");box.setAttribute("x",selector.x*options.sourceWidth);box.setAttribute("y",selector.y*options.sourceHeight);box.setAttribute("width",selector.width*options.sourceWidth);box.setAttribute("height",selector.height*options.sourceHeight);box.dataset.geometryAction="move-box";box.classList.add("ontobdc-annotation-geometry-box");overlay.append(box);[["nw",selector.x,selector.y],["ne",selector.x+selector.width,selector.y],["sw",selector.x,selector.y+selector.height],["se",selector.x+selector.width,selector.y+selector.height]].forEach(function(v){const h=svg("circle");h.setAttribute("cx",v[1]*options.sourceWidth);h.setAttribute("cy",v[2]*options.sourceHeight);h.setAttribute("r",7);h.dataset.geometryAction="resize-"+v[0];h.classList.add("ontobdc-annotation-geometry-handle");overlay.append(h);});}
    function setMode(value){mode=value;} function clear(){selector=null;operation=null;draw();emit();} function setSelector(value){selector=value?JSON.parse(JSON.stringify(value)):null;draw();}
    // A pointerdown landing on an existing annotation marker (rendered in
    // the separate annotation overlay by annotation_renderer.js, tagged
    // with data-annotation-id) must not start creating/dragging geometry
    // here. Otherwise "point" mode (now the only reachable mode, since
    // Select was removed from the toolbar) immediately draws a new
    // draggable point handle exactly on top of the marker being clicked —
    // that handle then intercepts the following "click" event before it
    // ever reaches the marker's own click-to-select listener, so clicking
    // an existing note silently fails to load it into the form.
    stage.addEventListener("pointerdown",function(event){if(event.target.closest&&event.target.closest("[data-annotation-id]"))return;const p=position(event),action=event.target.dataset.geometryAction;if(mode==="select"&&action){operation={action:action,start:p,original:copy(),index:Number(event.target.dataset.geometryIndex)};stage.setPointerCapture(event.pointerId);return;}if(mode==="point"){selector={type:"PointSelector",sourceWidth:options.sourceWidth,sourceHeight:options.sourceHeight,points:[p]};draw();emit();return;}if(mode==="multiple-points"){if(!selector||!selector.type.endsWith("PointSelector"))selector={type:"PointSelector",sourceWidth:options.sourceWidth,sourceHeight:options.sourceHeight,points:[]};selector.points.push(p);draw();emit();return;}if(mode==="bounding-box"){operation={action:"create-box",start:p};selector={type:"BoundingBoxSelector",sourceWidth:options.sourceWidth,sourceHeight:options.sourceHeight,x:p.x,y:p.y,width:.001,height:.001};stage.setPointerCapture(event.pointerId);draw();}});
    stage.addEventListener("pointermove",function(event){if(!operation)return;const p=position(event),dx=p.x-operation.start.x,dy=p.y-operation.start.y;if(operation.action==="create-box"){selector.x=Math.min(operation.start.x,p.x);selector.y=Math.min(operation.start.y,p.y);selector.width=Math.max(.001,Math.abs(dx));selector.height=Math.max(.001,Math.abs(dy));}else if(operation.action==="move-point"){selector.points[operation.index]={x:p.x,y:p.y};}else if(operation.action==="move-box"){selector.x=clamp(Math.min(1-operation.original.width,operation.original.x+dx));selector.y=clamp(Math.min(1-operation.original.height,operation.original.y+dy));}else{const o=operation.original,left=operation.action.endsWith("nw")||operation.action.endsWith("sw"),top=operation.action.endsWith("nw")||operation.action.endsWith("ne"),right=o.x+o.width,bottom=o.y+o.height;selector.x=left?Math.min(p.x,right-.001):o.x;selector.y=top?Math.min(p.y,bottom-.001):o.y;selector.width=left?right-selector.x:Math.max(.001,p.x-o.x);selector.height=top?bottom-selector.y:Math.max(.001,p.y-o.y);selector.width=Math.min(selector.width,1-selector.x);selector.height=Math.min(selector.height,1-selector.y);}draw();});
    stage.addEventListener("pointerup",function(event){if(!operation)return;operation=null;if(stage.hasPointerCapture(event.pointerId))stage.releasePointerCapture(event.pointerId);emit();});
    return Object.freeze({clear:clear,draw:draw,getSelector:copy,setMode:setMode,setSelector:setSelector});
  }
  global.OntoBDCAnnotationGeometryController=Object.freeze({createController:createController});
}(globalThis));
